define([
  '../../js/services/localdb-service.js',
  '../../js/services/websocket-service.js',
  '../../js/services/user-ui-service.js',
  '../../js/services/marketplace-ui-service.js',
	'../../js/services/user-login-ui-service.js',
	'../../js/services/resource-ui-service.js',
	'../../js/services/solution-ui-service.js',
	'../../js/services/dictionary-service.js',
  '../../js/services/unit-service.js',
  '../../js/services/view-flex-service.js',
	'../../js/services/dashboard-service.js',
	'../../js/services/ticket-service.js',
	'../../js/services/kpidata-flex-service.js',
	'../../js/services/model-definition-service.js',
	'../../js/services/config-ui-service.js',
	'../../js/services/ps-message-service.js',
	'../../js/services/user-init-service.js'
], function() {});