define([
	'../../js/services/user-login-ui-service.js',
	'../../js/services/localdb-service.js',
	'../../js/services/websocket-service.js',
	'../../js/services/view-flex-service.js',
	'../../js/services/resource-ui-service.js',
	'../../js/services/kpidata-flex-service.js',
	'../../js/services/user-domain-service.js',
	'../../js/services/solution-ui-service.js',
	'../../js/services/alert-query-service.js',
	'../../js/services/dictionary-service.js',
	'../../js/services/ticket-service.js',
	'../../js/services/user-enterprise-service.js',
	'../../js/services/work-flow-definition-service.js',
	'../../js/services/work-flow-service.js',
	'../../js/services/ticket-task-service.js',
	'../../js/services/ticket-log-service.js',
	'../../js/services/unit-service.js'
], function() {});